# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29249490bbf8485eaed340e7d47545045ec790fd0521eb044c86ece24db5e24c2b22514ca4ce84f6c22d734a408b4c6010708bb3e96bd25886c669f283b54ec9

test:
  secret_key_base: 1f5fa755d05a6727e10f402dc117661f9152a9dbdcbee03456a9f9ca2ed68522a7ed41cf1846da181bae52cee6b9f784972c73d79760d329e5bef97b6a708480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
